os:
  - linux
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid-fallback
git:
  depth: 3
env:
  - FLUTTER_VERSION=stable
before_script:
  - git clone https://github.com/flutter/flutter.git -b $FLUTTER_VERSION
  - ./flutter/bin/flutter doctor
script:
  - mv lib/config/config_example.dart lib/config/config.dart
  - ./flutter/bin/flutter test
cache:
  directories:
    - $HOME/.pub-cache
notifications:
  email:
    trongdinh@mroomsoft.com
branches:
  only: [master]